apiVersion: v1
kind: Service
metadata:
  name: secure-app-service
  namespace: secure-apps
spec:
  type: ClusterIP
  selector:
    app: secure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
